### ISSUE TITLE
Hang Man Game using Python

### ISSUE THREAD

**Issue by arinjain373** [Haritsdev0981/share-your-code#10]
I would like to add Hang Man Game using Python, under HacktoberFest-2022. Can you please assign it to me.

**Comment by Haritsdev0981** [comment]
> I would like to add Hang Man Game using Python, under HacktoberFest-2022. Can you please assign it to me.

sure..

**Comment by anshulraigh** [comment]
i've created [Simon Game](https://anshul02092003.github.io/Simon-Game/) is there any issue for it where i can share my code

**Comment by Haritsdev0981** [comment]
when I try your game, sometimes when I click the game button. game is automatically over.

**Comment by anshulraigh** [comment]
@Haritsdev0981 
here are steps to play game --
1) press any key to start game 
2) observe blinking color (if green)
3) press that blinked color (press green)
4) re-observe blinking color (if yellow)
5) press previous blinked color than current one (press green than yellow)
